---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.project }}-{{ .Values.app.tier }}"
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.project }}-{{ .Values.app.tier }}"
  minReplicas: {{ .Values.app.hpa.min }}
  maxReplicas: {{ .Values.app.hpa.max }}
  targetCPUUtilizationPercentage: {{ .Values.app.hpa.cpuTarget }}

...