---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.project }}-{{ .Values.app.tier }}"
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.app.ingress.host }}
    http:
      paths:
      - path: {{ .Values.app.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.project }}-{{ .Values.app.tier }}"
            port:
              number: {{ .Values.app.service.port }}

...