---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.project }}-{{ .Values.app.tier }}"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Values.project }}-{{ .Values.app.tier }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Values.project }}-{{ .Values.app.tier }}"
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  type: {{ .Values.app.service.type }}

...